### ISSUE TITLE
API: track if a user has ever `subscribed`

### ISSUE THREAD

**Issue by GreyMatteOr** [GreyMatteOr/Crate#14]
### when a user subscribes to a crate (request `operation` is `'subscriptionCreate'`):
  1. modify response to include if the user-client has ever sent a `subscriptionCreate` request before. (expect boolean)
  - possible backend entry-file: `/code/api/src/modules/subscription/resolvers`
  - frontend action location: `/code/web/src/modules/subscription/api/actions`

- [ ] Create an endpoint for mutating a user's `style` atttribute

**Comment by lkriffell** [comment]
Could this be done by checking that a user has a `style`  attribute that is not nil?

**Comment by GreyMatteOr** [comment]
@ikriffell Nearly. The edge-case is: what if someone doesn't finish their survey? 

If they don't complete it, then their `style` will still be `null` / `nil`, and so the next time they click the subscribe button, they will be forced to take the survey again. EX: They hit subscribe, get sent to the survey, they hit the 'back' button because they don't wanna, but then when they click the button again, they are forced to anyway.
 
By the wording of our track, we are NOT supposed to force our user after the first time. So if they don't complete it, we can assume they aren't interested? 

I'm unclear on the backend 'types', but in JS there is `undefined` and there is `null` so maybe if the `style` property is `undefined` we can assume it's their first time. Then when they take the survey for the first time, we set it to `null` which represents that they saw the survey but don't want it. Any other value would of course indicate they completed the survey and also don't need to be taken to that screen again.

**Comment by lkriffell** [comment]
@GreyMatteOr Okay. I talked with the BE and they cleared this up for me that the survey isn't necessary for a user to subscribe to a crate, but it's optional if a user wants more tailored results in their crate
