### ISSUE TITLE
User Story: In SurveyOverview, display all selections from SurveyPages

### ISSUE THREAD

**Issue by bretm9** [GreyMatteOr/Crate#44]
As a user, when brought to the overview page, I should be able to see all the selections I made on the survey pages

**Comment by GreyMatteOr** [comment]
![Overview_top](https://user-images.githubusercontent.com/65369751/101272196-d8384b00-373e-11eb-8b35-89080eae39fa.png)
![Overview_middle](https://user-images.githubusercontent.com/65369751/101272197-d9697800-373e-11eb-9aaa-761bb64858f8.png)
![Overview_bottom](https://user-images.githubusercontent.com/65369751/101272198-d9697800-373e-11eb-9674-4a2026c04748.png)
![Overview_top_proto](https://user-images.githubusercontent.com/65369751/101272199-da020e80-373e-11eb-80ed-d66f157febeb.png)
![Overview_bottom_proto](https://user-images.githubusercontent.com/65369751/101272200-da020e80-373e-11eb-9574-637a2d18d1f3.png)
